# Generated by Django 4.2.2 on 2023-06-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Материал')),
                ('url', models.SlugField(max_length=260, unique=True)),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Материалнинг тўқилиш тури',
                'verbose_name_plural': 'Материалларнинг тўқилиш тури',
            },
        ),
        migrations.AlterModelOptions(
            name='weightmaterial',
            options={'verbose_name': 'Материалнинг оғирлиги ', 'verbose_name_plural': 'Материалларнинг оғирлиги '},
        ),
        migrations.AlterField(
            model_name='weightmaterial',
            name='material',
            field=models.CharField(max_length=250, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='weightmaterial',
            name='weight',
            field=models.CharField(max_length=250, verbose_name='Оғирлиги'),
        ),
    ]
