# Generated by Django 4.2.2 on 2023-06-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_typematerial_alter_weightmaterial_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Материалнинг толавий таркиби')),
                ('url', models.SlugField(max_length=260, unique=True)),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Материалнинг толавий таркиби ',
                'verbose_name_plural': 'Материалнинг толавий таркиби',
            },
        ),
    ]
