# Generated by Django 4.2.2 on 2023-06-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_contentmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorsMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Материалнинг ранги номи ')),
                ('photo', models.ImageField(upload_to='jeanscolor/', verbose_name='Изображение')),
                ('url', models.SlugField(max_length=260, unique=True)),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Материалнинг ранги ',
                'verbose_name_plural': 'Материалларнинг ранглари ',
            },
        ),
    ]
