# Generated by Django 4.2.2 on 2023-06-23 11:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_colorsmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Химикат номи\t')),
                ('chemicalformul', models.CharField(blank=True, default=None, max_length=250, verbose_name='Кимевий формуласи')),
                ('view', models.ImageField(upload_to='chemicalcolors/', verbose_name='Расм\t')),
                ('varki', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Количество для типа варки, гр')),
                ('url', models.SlugField(max_length=260, unique=True)),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Химикат номи, тури ',
                'verbose_name_plural': 'Химикатлар номлари, турлари ',
            },
        ),
    ]
