# Generated by Django 4.2.2 on 2023-06-23 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_countryname'),
    ]

    operations = [
        migrations.CreateModel(
            name='SewingThreads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradethread', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Название сорт  (100% РЕ)')),
                ('modelthread', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Название модель')),
                ('photo', models.ImageField(upload_to='threadphoto/', verbose_name='Вид\t')),
                ('url', models.SlugField(max_length=260, unique=True)),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.countryname', verbose_name='Название страна')),
            ],
            options={
                'verbose_name': 'Швейные нитки тип ',
                'verbose_name_plural': 'Швейные нитки тип ',
            },
        ),
        migrations.CreateModel(
            name='DecorativeThreads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradethread', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Название сорт  (100% РЕ)')),
                ('modelthread', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Название модель')),
                ('photo', models.ImageField(upload_to='decorphoto/', verbose_name='Вид\t')),
                ('url', models.SlugField(max_length=260, unique=True)),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='order.countryname', verbose_name='Название страна')),
            ],
            options={
                'verbose_name': 'Декоратив нитки тип ',
                'verbose_name_plural': 'Декоратив нитки тип ',
            },
        ),
    ]
