# Generated by Django 4.2.2 on 2023-06-23 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_sewingthreads_decorativethreads'),
    ]

    operations = [
        migrations.CreateModel(
            name='DlinaMolniy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Длина Молния')),
                ('url', models.SlugField(max_length=260, unique=True)),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Молния Длина ',
                'verbose_name_plural': 'Молния Длина ',
            },
        ),
        migrations.AlterModelOptions(
            name='decorativethreads',
            options={'verbose_name': 'Безак чокни тикиш учун ип намунаси', 'verbose_name_plural': 'Безак чокларни тикиш учун иплар намунаси'},
        ),
        migrations.AlterModelOptions(
            name='sewingthreads',
            options={'verbose_name': 'Ички чокни тикиш учун ип намунаси ', 'verbose_name_plural': 'Ички чокларни тикиш учун иплар намунаси'},
        ),
        migrations.CreateModel(
            name='Molniya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelmolniy', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Название модель')),
                ('gradethread', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Название сорт  (100% РЕ)')),
                ('colormolniy', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Название Цвет')),
                ('zvena', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Название Материал звена')),
                ('colorzvena', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Название Цвет звена')),
                ('photo', models.ImageField(upload_to='molniyphoto/', verbose_name='Молния\t')),
                ('url', models.SlugField(max_length=260, unique=True)),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('molniydilin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.dlinamolniy', verbose_name='Длина Молния ')),
            ],
            options={
                'verbose_name': 'Молния  тип ',
                'verbose_name_plural': 'Молния  тип ',
            },
        ),
    ]
