# Generated by Django 4.2.2 on 2023-06-23 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_dlinamolniy_alter_decorativethreads_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='molniya',
            name='gradethread',
        ),
    ]
