# Generated by Django 4.2.2 on 2023-06-23 18:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_molniya_gradethread'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knopok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelknopok', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Название модель')),
                ('materialknopok', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Материал)')),
                ('diametrknopok', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Диаметр  ')),
                ('colorknopok', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Название Цвет')),
                ('photo', models.ImageField(upload_to='knopokphoto/', verbose_name='Пуговицы\t')),
                ('url', models.SlugField(max_length=260, unique=True)),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kнопок  тип ',
                'verbose_name_plural': 'Kнопок  тип ',
            },
        ),
        migrations.CreateModel(
            name='Zaklepka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materialzaklepka', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Материал)')),
                ('diametrzaklepka', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Диаметр  ')),
                ('colorzaklepka', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Название Цвет')),
                ('photo', models.ImageField(upload_to='zaklepkaphoto/', verbose_name='Заклепки\t')),
                ('url', models.SlugField(max_length=260, unique=True)),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Заклепка  тип ',
                'verbose_name_plural': 'Заклепка  тип ',
            },
        ),
    ]
