# Generated by Django 4.2.2 on 2023-06-23 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_knopok_zaklepka'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='F.I.O')),
                ('organization', models.CharField(max_length=250, verbose_name='Tashkiloti')),
                ('phone', models.CharField(max_length=250, verbose_name='Telefon nomer')),
                ('email', models.CharField(max_length=250, verbose_name='Elektron pochta')),
                ('adrres', models.CharField(max_length=250, verbose_name='Manzili')),
                ('url', models.SlugField(max_length=260, unique=True)),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CostumerRecommen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Buyurtma raqami ')),
                ('url', models.SlugField(max_length=260, unique=True)),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('chemicalname', models.ManyToManyField(to='order.chemicalname', verbose_name='Химикатлар номи, тури')),
                ('colorsmaterial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.colorsmaterial', verbose_name='Материалнинг ранги')),
                ('contentmaterial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.contentmaterial', verbose_name='Материалнинг толавий таркиби')),
                ('costumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.costumer', verbose_name='Mijoz')),
                ('decorativethreads', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.decorativethreads', verbose_name='Безак чокларни тикиш учун иплар намунаси')),
                ('knopok', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.knopok', verbose_name='Тугма турлари')),
                ('molniya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.molniya', verbose_name='Молния тақилма')),
                ('sewingthreads', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.sewingthreads', verbose_name='Ички чокларни тикиш учун иплар намунаси')),
                ('typematerial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.typematerial', verbose_name='Материалнинг тўқилиш туриz')),
                ('weightmaterial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.weightmaterial', verbose_name='Материалнинг оғирлиги')),
                ('zaklepka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.zaklepka', verbose_name='Заклепка турлари')),
            ],
            options={
                'verbose_name': 'Mijozga tavsiya ',
                'verbose_name_plural': 'Mijozlarga tavsiyalar ',
            },
        ),
    ]
